name: my_simple_note
description: "A new Flutter project."
publish_to: 'none' 

# Application versioning
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.17.0

  cupertino_icons: ^1.0.8
  sqflite: ^2.0.0+3  # For local SQLite database
  path: ^1.8.2       # For working with file paths

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  

# Flutter-specific settings
flutter:
  uses-material-design: true
